---

- hosts: elasticsearch
  user: golpa
  become: true
  become_user: root
  roles:
    - elasticsearch
    - configure_logstash

- hosts: kibana
  user: golpa
  become: true
  become_user: root
  roles:
    - kibana
    - configure_kibana

- hosts: webs
  user: golpa
  become: true
  become_user: root
  roles:
    - install_filebeat
    - configure_filebeat
