---

- hosts: grafana
  user: golpa
  become: true
  become_user: root
  roles:
    - grafana
    - configure_prom

- hosts: grafana
  user: golpa
  become: true
  become_user: root
  roles:
    - configure_prom